### ISSUE TITLE
Got no other variant to connect you :)

### ISSUE THREAD

**Issue by arizorin** [kazbeel/qmk#1]
Hello @kazbeel , do you have any progress on https://stackoverflow.com/questions/71672331/know-socket-io-event-name-when-handling-an-error-on-nestjs-websocketgateway?newreg=a84173b80e9e404189b99c36cc7d0296 ? Just ran into the same problem(

P.S Sry for not an appropriate place for a question

**Comment by kazbeel** [comment]
Hi there. I'm afraid that I have finally faced the problem from another point of view so I cannot help you much in that matter. Nonetheless, I investigated a little about how to get the name from the decorator `@SubscribeMessage` without much success. It is not possible to do it (at least apparently). I recommend you to ask in the NestJS forum.
Good luck.

**Comment by arizorin** [comment]
Okey, thanks
